// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRxV6gpm-nwdXvC5R82_qISPYyfpdb7Q',
    appId: '1:491326037563:web:bd06301e38e6cf79c9c61e',
    messagingSenderId: '491326037563',
    projectId: 'uas-ambw-34770',
    authDomain: 'uas-ambw-34770.firebaseapp.com',
    storageBucket: 'uas-ambw-34770.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUu-ATr67sWHos9fKG1Oj7ZHEBBqwVmXQ',
    appId: '1:491326037563:android:a8f650b2692e2622c9c61e',
    messagingSenderId: '491326037563',
    projectId: 'uas-ambw-34770',
    storageBucket: 'uas-ambw-34770.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Mybb9tT7BntIH1teFjXz4FzBOtM60E0',
    appId: '1:491326037563:ios:5a5924c5d6cb34f0c9c61e',
    messagingSenderId: '491326037563',
    projectId: 'uas-ambw-34770',
    storageBucket: 'uas-ambw-34770.firebasestorage.app',
    iosBundleId: 'com.example.c14210103KevinUasAmbw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Mybb9tT7BntIH1teFjXz4FzBOtM60E0',
    appId: '1:491326037563:ios:5a5924c5d6cb34f0c9c61e',
    messagingSenderId: '491326037563',
    projectId: 'uas-ambw-34770',
    storageBucket: 'uas-ambw-34770.firebasestorage.app',
    iosBundleId: 'com.example.c14210103KevinUasAmbw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWRxV6gpm-nwdXvC5R82_qISPYyfpdb7Q',
    appId: '1:491326037563:web:cc2923cdbeffbb57c9c61e',
    messagingSenderId: '491326037563',
    projectId: 'uas-ambw-34770',
    authDomain: 'uas-ambw-34770.firebaseapp.com',
    storageBucket: 'uas-ambw-34770.firebasestorage.app',
  );
}
